[package]
name = "game-rs"
version = "0.1.11-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]] 
name="game-rs"
path="src/game_main.rs"

[dependencies]
