name: package_release

on:
  push:
    tags:
      - "*-test"
#      - "*-alpha"
#      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run cargo build --release
        uses: actions-rs/cargo@v1
#        working-directory: game-rs # only works in run and shell steps
        with:
          command: build
          args: --release --manifest-path game-rs/Cargo.toml
