name: package_release

on:
  push:
    tags:
      - "*-test"
#      - "*-alpha"
#      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: aarch64-apple-darwin

#      - name: Install cargo-get
#        uses: actions-rs/cargo@v1
#        with:
#          command: install
#          args: cargo-get
#

      - name: Run cargo build --release for x86
        uses: actions-rs/cargo@v1
#        working-directory: game-rs # only works in run and shell steps
        with:
          command: build
          args: --release --manifest-path game-rs/Cargo.toml --target x86_64-apple-darwin

      - name: Run cargo build --release for M1
        uses: actions-rs/cargo@v1
#        working-directory: game-rs # only works in run and shell steps
        with:
          command: build
          args: --release --manifest-path game-rs/Cargo.toml --target aarch64-apple-darwin

      - name: Package MacOS .app
        run: ./package_macos.sh
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-app-${{ github.ref_name }}
          path: package/

